// Generated by CMake (SCARAB_ASAN_DEFAULT_OPTIONS in src/CMakeLists.txt).
extern "C" const char *__asan_default_options(void) {
  return "check_initialization_order=true:detect_stack_use_after_return=true:strict_string_checks=true";
}
